import: com.kainos.ea.ggdd.database.properties

language: java
jdk: openjdk14
cache:
  directories: $HOME/.m2
notifications:
  email:
    recipients: recipients
    on_failure: always
    on_success: never